ASK WHERE {
 <http://localhost:8888/tests/xml/0106.xml> <http://purl.org/dc/elements/1.1/creator>  ?a .
 OPTIONAL {
   ?x ?y <http://localhost:8888/tests/xml/manu.html> .
 }
 FILTER (isBlank(?a) && !BOUND(?x) && !BOUND(?y))
}
