PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>

ASK WHERE {
<_:1> xhv:alternate "alternate" .
<_:1> xhv:appendix "appendix" .
<_:1> xhv:cite "cite" .
<_:1> xhv:bookmark "bookmark" .
<_:1> xhv:contents "contents" .
<_:1> xhv:chapter "chapter" .
<_:1> xhv:copyright "copyright" .
<_:1> xhv:first "first" .
<_:1> xhv:glossary "glossary" .
<_:1> xhv:help "help" .
<_:1> xhv:icon "icon" .
<_:1> xhv:index "index" .
<_:1> xhv:last "last" .
<_:1> xhv:license "license" .
<_:1> xhv:meta "meta" .
<_:1> xhv:next "next" .
<_:1> xhv:prev "prev" .
<_:1> xhv:previous "previous" .
<_:1> xhv:section "section" .
<_:1> xhv:start "start" .
<_:1> xhv:stylesheet "stylesheet" .
<_:1> xhv:subsection "subsection" .
<_:1> xhv:top "top" .
<_:1> xhv:up "up" .
<_:1> xhv:p3pv1 "p3pv1" .
}
