ASK WHERE {
	<_:1> <http://xmlns.com/foaf/0.1/mbox> <mailto:manu.sporny@digitalbazaar.com> .
	<_:2> <http://xmlns.com/foaf/0.1/mbox> <mailto:michael.hausenblas@joanneum.at> .
	<_:1> <http://xmlns.com/foaf/0.1/knows> <_:2> .
}
